/**
 * Canonical genre → representative artist mapping used in onboarding seeding
 * and taste-engine genre-shift mode. Kept here so both layers share the same data.
 */
export const GENRE_ARTISTS: Record<string, string[]> = {
  'Pop':         ['Taylor Swift', 'Ed Sheeran', 'Dua Lipa'],
  'Rock':        ['Arctic Monkeys', 'Foo Fighters', 'The Killers'],
  'Hip-Hop':     ['Kendrick Lamar', 'Drake', 'J. Cole'],
  'Electronic':  ['Daft Punk', 'Calvin Harris', 'Disclosure'],
  'R&B / Soul':  ['The Weeknd', 'Frank Ocean', 'SZA'],
  'Indie':       ['Tame Impala', 'Vampire Weekend', 'Bon Iver'],
  'Metal':       ['Metallica', 'System of a Down', 'Tool'],
  'Jazz':        ['Miles Davis', 'John Coltrane', 'Herbie Hancock'],
  'Country':     ['Morgan Wallen', 'Chris Stapleton', 'Luke Combs'],
  'Latin':       ['Bad Bunny', 'J Balvin', 'Maluma'],
  'Classical':   ['Ludovico Einaudi', 'Hans Zimmer', 'Max Richter'],
  'Reggae':      ['Bob Marley', 'Damian Marley', 'Chronixx'],
  'Dance':       ['Calvin Harris', 'Kygo', 'Martin Garrix'],
  'Blues':       ['B.B. King', 'Eric Clapton', 'Gary Clark Jr.'],
  'Punk':        ['Green Day', 'Blink-182', 'The Offspring'],
  'Alternative': ['Radiohead', 'Muse', 'Cage The Elephant'],
  'Trap':        ['Travis Scott', 'Future', '21 Savage'],
  'Lo-fi':       ['Nujabes', 'Joji', 'Idealism'],
  'K-Pop':       ['BTS', 'BLACKPINK', 'Stray Kids'],
  'Afrobeats':   ['Burna Boy', 'Wizkid', 'Rema'],
  'Phonk':       ['Kordhell', 'Freddie Dredd', 'DVRST'],
  'Drill':       ['Central Cee', 'Pop Smoke', 'Headie One'],
  'Folk':        ['Hozier', 'Fleet Foxes', 'Mumford & Sons'],
  'Funk':        ['Anderson .Paak', 'Bruno Mars', 'Vulfpeck'],
  'Disco':       ['Doja Cat', 'Bee Gees', 'Nile Rodgers'],
  'Ambient':     ['Brian Eno', 'Tycho', 'Boards of Canada'],
  'Rap':         ['Eminem', 'Nas', 'Lil Wayne'],
  'Underground': ['Three 6 Mafia', 'MF DOOM', 'Earl Sweatshirt'],
  'Grunge':      ['Nirvana', 'Pearl Jam', 'Soundgarden'],
  'Reggaeton':   ['Daddy Yankee', 'Ozuna', 'Anuel AA'],
  'Techno':      ['Carl Cox', 'Amelie Lens', 'Charlotte de Witte'],
  'House':       ['Disclosure', 'Fisher', 'Chris Lake'],
  'Garage':      ['Craig David', 'Artful Dodger', 'DJ EZ'],
  'Dubstep':     ['Skrillex', 'Excision', 'Zomboy'],
  'Emo':         ['My Chemical Romance', 'Fall Out Boy', 'Paramore'],
  'Hardcore':    ['Knocked Loose', 'Turnstile', 'Terror'],
  'Synthwave':   ['The Midnight', 'Kavinsky', 'Perturbator'],
  'Gospel':      ['Kirk Franklin', 'Maverick City Music', 'Tasha Cobbs Leonard'],
  'Drum & Bass': ['Sub Focus', 'Andy C', 'Netsky'],
  'Grime':       ['Skepta', 'Stormzy', 'Wiley'],
};

export const GENRES = Object.keys(GENRE_ARTISTS);

export const GENRE_COLORS: Record<string, string> = {
  'Pop':         '#EC4899',
  'Rock':        '#EF4444',
  'Hip-Hop':     '#F59E0B',
  'Electronic':  '#22D3EE',
  'R&B / Soul':  '#A855F7',
  'Indie':       '#84CC16',
  'Metal':       '#94A3B8',
  'Jazz':        '#F97316',
  'Country':     '#D97706',
  'Latin':       '#F43F5E',
  'Classical':   '#60A5FA',
  'Reggae':      '#22C55E',
  'Dance':       '#8B5CF6',
  'Blues':       '#3B82F6',
  'Punk':        '#10B981',
  'Alternative': '#6366F1',
  'Trap':        '#DC2626',
  'Lo-fi':       '#78716C',
  'K-Pop':       '#F472B6',
  'Afrobeats':   '#FBBF24',
  'Phonk':       '#991B1B',
  'Drill':       '#475569',
  'Folk':        '#A3E635',
  'Funk':        '#E879F9',
  'Disco':       '#C084FC',
  'Ambient':     '#67E8F9',
  'Rap':         '#FB923C',
  'Underground': '#713F12',
  'Grunge':      '#737373',
  'Reggaeton':   '#FB7185',
  'Techno':      '#06B6D4',
  'House':       '#7C3AED',
  'Garage':      '#A78BFA',
  'Dubstep':     '#7F1D1D',
  'Emo':         '#1F2937',
  'Hardcore':    '#B91C1C',
  'Synthwave':   '#D946EF',
  'Gospel':      '#FDE68A',
  'Drum & Bass': '#14B8A6',
  'Grime':       '#334155',
};
